### PR TITLE
Allow OR operator in question/segment filter

### PR DESCRIPTION
**Pull request by matthieu-foucault**
Implementation of the feature requested in https://github.com/metabase/metabase/issues/3217

As the query builder is being rewritten, this is only a temporary solution.

### CODE REVIEW

**Comment by matthieu-foucault** [comment]
@hamzajaved Wanna take a look? (I can't request you as a reviewer for some reason)

**Comment by keshshri** [comment]
I have been waiting for this for quite some time. When could this be GA?

**Comment by matthieu-foucault** [comment]
The query builder interface was drastically changed upstream, and this design hasn't been approved by the Metabase maintainers. Unfortunately, I think it's going to remain an ad-hoc feature

**Comment by keshshri** [comment]
Could I get the jar file to test this too? I looked up and tested with new GUI and it doesn't look like the new GUI allows for an or operation discussed here

**Comment by wenzowski** [comment]
@keshav0129 we aren't currently releasing a jar file build of this feature, but you're certainly welcome to build [our fork](https://github.com/bcgov/cas-ggircs-metabase) by following the [instructions](https://github.com/metabase/metabase/blob/master/docs/developers-guide.md#build-metabase) in the developers guide. Please be aware that our fork is unstable and for development purposes only while we work towards an upstream contribution.

**Comment by keshshri** [comment]
@wenzowski thank you!

**Pull request merged**
